name: Deploy Child Theme

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List files
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Files in src directory:"
          ls -la src/
          echo "code in functions.php:"
          cat src/functions.php

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              # Production deployment
              rsync -avz --delete src/ ${{ secrets.REMOTE_PATH }}/wp-content/themes/twentytwentyfour-spenpo/
            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
              # Staging deployment
              rsync -avz --delete src/ ${{ secrets.REMOTE_PATH }}/staging/wp-content/themes/twentytwentyfour-spenpo/
            fi
