name: Deploy Child Theme

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set deployment path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_PATH=${{ secrets.REMOTE_PATH }}/wp-content/themes/twentytwentyfour-spenpo/" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=${{ secrets.REMOTE_PATH }}/staging/wp-content/themes/twentytwentyfour-spenpo/" >> $GITHUB_ENV
          fi

      - name: Deploy via Rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: ${{ env.DEPLOY_PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}
