name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -la

      - name: Deploy via rsync
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.PORT }}" ./src/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:domains/introspective20s.com/public_html/wp-content/themes/twentytwentyfour-spenpo/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

